apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector:
    app: posts # Expose this service
  ports:
    - name: posts
      protocol: TCP
      port: 4000 # Node Port outside to the service
      targetPort: 4000 # Inside the code PORT as the app in the index.js
